### Get
GET http://localhost:8080/category/a258f5e1-6022-47de-bbc4-00d43894b39c

### Create
POST http://localhost:8080/category/adm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkMDE5OWQ2YS05ODMxLTQwZDUtYjE4NC1lMTM0OTEwNGQ1YTgiLCJpYXQiOjE2NTI5NDA1ODMsImV4cCI6MTY1Mjk0NDE4MywiaXNzIjoibWF6Z2kgcHJvZHVjdGlvbiIsInJvbGUiOiJBRE1JTiJ9.ve5ljmDwvVh9jPO1zffS3EUxG6iFnYtBzosp7jproEQ

{
  "name": "Lashara"
}

### Update
PUT http://localhost:8080/category/adm/a258f5e1-6022-47de-bbc4-00d43894b39c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyNTM5ZDQzOS1lZmRlLTRhZmItOTkyNy1jOTliNGVhNGE3YzEiLCJpYXQiOjE2NTI1NTYwMjEsImV4cCI6MTY1MjU1OTYyMSwiaXNzIjoibWF6Z2kgcHJvZHVjdGlvbiIsInJvbGUiOiJBRE1JTiJ9.-3sRRohi1_bLiRs8PPhgOiUda9Bd4uR5m1O_b4TvLAk

{
  "name": "Test"
}

### Delete
DELETE http://localhost:8080/category/adm/a258f5e1-6022-47de-bbc4-00d43894b39c/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyNTM5ZDQzOS1lZmRlLTRhZmItOTkyNy1jOTliNGVhNGE3YzEiLCJpYXQiOjE2NTI1NTYwMjEsImV4cCI6MTY1MjU1OTYyMSwiaXNzIjoibWF6Z2kgcHJvZHVjdGlvbiIsInJvbGUiOiJBRE1JTiJ9.-3sRRohi1_bLiRs8PPhgOiUda9Bd4uR5m1O_b4TvLAk

### List
GET http://localhost:8080/category/public
