### Get
GET http://localhost:8080/channel/96a9adff-715f-46f7-8742-5bb502b2781d

### Create
POST http://localhost:8080/channel/public
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwODNjZTAxYi00NDNjLTRmNzUtOGNkMC0yNjE1MzY2Njg2YjEiLCJpYXQiOjE2NTI5NDExMjAsImV4cCI6MTY1Mjk0NDcyMCwiaXNzIjoibWF6Z2kgcHJvZHVjdGlvbiIsInJvbGUiOiJVU0VSIn0.2XdqENEAP_GxYRYwuXsNm5m5OZ0W8DcKHDrmI7XvTxI

{
  "name": "toshmatUz",
  "description": ""
}

### Update Bio
PUT http://localhost:8080/channel/public/0d664c18-c53a-41e6-b4f8-1c8d84273450
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyNTM5ZDQzOS1lZmRlLTRhZmItOTkyNy1jOTliNGVhNGE3YzEiLCJpYXQiOjE2NTI4ODAxNjQsImV4cCI6MTY1Mjg4Mzc2NCwiaXNzIjoibWF6Z2kgcHJvZHVjdGlvbiIsInJvbGUiOiJBRE1JTiJ9.X3_ZtysG-mihZCCRvVNWLsNQNfY-t3ycye7LAxHLmu8

{
  "name": "Java",
  "description": "Test Channel"
}

### Image
PUT http://localhost:8080/channel/public/image/96a9adff-715f-46f7-8742-5bb502b2781d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwODNjZTAxYi00NDNjLTRmNzUtOGNkMC0yNjE1MzY2Njg2YjEiLCJpYXQiOjE2NTI5NDExMjAsImV4cCI6MTY1Mjk0NDcyMCwiaXNzIjoibWF6Z2kgcHJvZHVjdGlvbiIsInJvbGUiOiJVU0VSIn0.2XdqENEAP_GxYRYwuXsNm5m5OZ0W8DcKHDrmI7XvTxI

{
  "id": "1ab6ac18-89c4-4531-8ea4-3d1208d9a2a8"
}

### Banner
PUT http://localhost:8080/channel/public/banner/96a9adff-715f-46f7-8742-5bb502b2781d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwODNjZTAxYi00NDNjLTRmNzUtOGNkMC0yNjE1MzY2Njg2YjEiLCJpYXQiOjE2NTI5NDExMjAsImV4cCI6MTY1Mjk0NDcyMCwiaXNzIjoibWF6Z2kgcHJvZHVjdGlvbiIsInJvbGUiOiJVU0VSIn0.2XdqENEAP_GxYRYwuXsNm5m5OZ0W8DcKHDrmI7XvTxI

{
  "id": "1a17c2d8-b01d-499e-8ec3-cc9d4faad5c9"
}

### Profile Channel List
GET http://localhost:8080/channel/public/list
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwODNjZTAxYi00NDNjLTRmNzUtOGNkMC0yNjE1MzY2Njg2YjEiLCJpYXQiOjE2NTI5NDExMjAsImV4cCI6MTY1Mjk0NDcyMCwiaXNzIjoibWF6Z2kgcHJvZHVjdGlvbiIsInJvbGUiOiJVU0VSIn0.2XdqENEAP_GxYRYwuXsNm5m5OZ0W8DcKHDrmI7XvTxI

### Delete
DELETE http://localhost:8080/channel/public/0d664c18-c53a-41e6-b4f8-1c8d84273450/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyNTM5ZDQzOS1lZmRlLTRhZmItOTkyNy1jOTliNGVhNGE3YzEiLCJpYXQiOjE2NTI4ODAxNjQsImV4cCI6MTY1Mjg4Mzc2NCwiaXNzIjoibWF6Z2kgcHJvZHVjdGlvbiIsInJvbGUiOiJBRE1JTiJ9.X3_ZtysG-mihZCCRvVNWLsNQNfY-t3ycye7LAxHLmu8

### Change Status
PUT http://localhost:8080/channel/public/status/0d664c18-c53a-41e6-b4f8-1c8d84273450
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyNTM5ZDQzOS1lZmRlLTRhZmItOTkyNy1jOTliNGVhNGE3YzEiLCJpYXQiOjE2NTI4ODAxNjQsImV4cCI6MTY1Mjg4Mzc2NCwiaXNzIjoibWF6Z2kgcHJvZHVjdGlvbiIsInJvbGUiOiJBRE1JTiJ9.X3_ZtysG-mihZCCRvVNWLsNQNfY-t3ycye7LAxHLmu8

### List
GET http://localhost:8080/channel/adm/list
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwODNjZTAxYi00NDNjLTRmNzUtOGNkMC0yNjE1MzY2Njg2YjEiLCJpYXQiOjE2NTI5NDExMjAsImV4cCI6MTY1Mjk0NDcyMCwiaXNzIjoibWF6Z2kgcHJvZHVjdGlvbiIsInJvbGUiOiJVU0VSIn0.2XdqENEAP_GxYRYwuXsNm5m5OZ0W8DcKHDrmI7XvTxI
